# Generated by Django 5.1.5 on 2025-01-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StockInvestment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockinvestment",
            name="analysis_report",
            field=models.TextField(blank=True, null=True),
        ),
    ]
