# Generated by Django 5.1.5 on 2025-01-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("StockInvestment", "0002_alter_stockinvestment_analysis_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockinvestment",
            old_name="analysis_report",
            new_name="investment_report",
        ),
    ]
