# Generated by Django 5.1.5 on 2025-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockInvestment', '0003_rename_analysis_report_stockinvestment_investment_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinvestment',
            name='api_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
