# Generated by Django 5.1.5 on 2025-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockAnalysis', '0002_alter_stockanalysis_analysis_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='api_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
