# Generated by Django 5.1.5 on 2025-04-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockAnalysis', '0004_userprofile'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE StockAnalysis_userprofile ADD COLUMN API_key varchar(100) NULL;
            """,
            reverse_sql="""
            ALTER TABLE StockAnalysis_userprofile DROP COLUMN API_key;
            """
        ),
    ]
