# Generated by Django 5.1.5 on 2025-04-17 17:09

from django.db import migrations

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('StockAnalysis', 'UserProfile')
    
    for user in User.objects.all():
        # Check if the user already has a profile
        if not UserProfile.objects.filter(user=user).exists():
            UserProfile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('StockAnalysis', '0005_auto_20250417_1707'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
